from pathlib import Path
import re
p=Path('index.html');s=p.read_text()
s,n=re.subn(r"async function rpcCloud\(path,options=\{\}\)\{.*?\n(?=async function completeMFAIfRequired)","async function rpcCloud(path,options={}){if(!rpcSupabase)throw new Error('SUPABASE_CLIENT_UNAVAILABLE');const {data:{session}}=await rpcSupabase.auth.getSession();if(!session?.access_token)return null;const {data,error}=await rpcSupabase.functions.invoke('romano-api',{method:options.method||'GET',body:options.body,headers:{'x-rpc-path':String(path||''),...(options.headers||{})}});if(error)throw error;return data;}\n",s,count=1,flags=re.S)
print('rpc',n)
login="""async function directAuthContext(user){const {data,error}=await rpcSupabase.from('user_profiles').select('role,display_name,active,company_id,employee_id,client_id').eq('id',user.id).maybeSingle();if(error)throw error;if(!data||data.active===false)throw new Error('USUARIO_INACTIVO');return data;}\nasync function login(ev){ev.preventDefault();let loginValue=q('loginEmail').value.trim().toLowerCase(),pass=q('loginPassword').value;q('authError').style.display='none';try{if(rpcSupabase){let realEmail=TEST_EMAIL_MAP[loginValue]||loginValue;let {data,error}=await rpcSupabase.auth.signInWithPassword({email:realEmail,password:pass});if(error)throw error;if(data?.user){await completeMFAIfRequired();let c=await directAuthContext(data.user);currentRole=String(c.role||'ADMIN').replace('FUNCIONÁRIO','FUNCIONARIO');currentUser={id:data.user.id,email:data.user.email,name:c.display_name||data.user.email,displayName:c.display_name||data.user.email,role:currentRole,company_id:c.company_id,employeeId:c.employee_id||null,clientId:c.client_id||null};sessionStorage.setItem('RPC_V78_SESSION',JSON.stringify(currentUser));q('authScreen').style.display='none';applyRoleUI();go(roleHome());await loadCloudState(false);if(typeof syncAuthEmployeeIntoDb==='function')syncAuthEmployeeIntoDb();save();await initCloudRealtime();return;}}}catch(err){console.warn('login',err);try{await rpcSupabase?.auth.signOut()}catch{}q('authError').textContent=err?.message==='USUARIO_INACTIVO'?'Usuario inactivo o sin perfil habilitado.':'E-mail o contraseña incorrectos.';q('authError').style.display='block';return}let a=TEST_ACCOUNTS[loginValue];if(!a||a.password!==pass){q('authError').textContent='No se pudo iniciar sesión con esa cuenta. Comprueba correo, contraseña o MFA.';q('authError').style.display='block';return}currentRole=a.role;currentUser={email:loginValue,name:a.name,role:a.role,devMode:true};sessionStorage.setItem('RPC_V78_SESSION',JSON.stringify(currentUser));q('authScreen').style.display='none';applyRoleUI();go(roleHome());toast('Sesión de prueba · '+a.role)}\n"""
s,n=re.subn(r"async function login\(ev\)\{.*?\nfunction roleHome\(\)",login+'function roleHome()',s,count=1,flags=re.S);print('login',n)
s,n=re.subn(r"function roleHome\(\)\{.*?\}","function roleHome(){if(currentRole==='CLIENTE')return 'dashboard';if(currentRole==='SUPERVISOR')return 'employee';if(currentRole==='FUNCIONARIO')return 'employee';return 'dashboard'}",s,count=1,flags=re.S);print('home',n)
restore="""async function restoreSession(){try{if(rpcSupabase){let {data:{session}}=await rpcSupabase.auth.getSession();if(session?.user){let c=await directAuthContext(session.user);currentUser={id:session.user.id,email:session.user.email,name:c.display_name||session.user.email,displayName:c.display_name||session.user.email,role:String(c.role||'ADMIN').replace('FUNCIONÁRIO','FUNCIONARIO'),company_id:c.company_id,employeeId:c.employee_id||null,clientId:c.client_id||null};currentRole=currentUser.role;q('authScreen').style.display='none';applyRoleUI();go(roleHome());await loadCloudState(false);if(typeof syncAuthEmployeeIntoDb==='function')syncAuthEmployeeIntoDb();await initCloudRealtime();return true;}}let u=JSON.parse(sessionStorage.getItem('RPC_V78_SESSION')||'null');if(u&&TEST_ACCOUNTS[u.email]){currentUser=u;currentRole=u.role;q('authScreen').style.display='none';applyRoleUI();go(roleHome());return true}}catch(e){console.warn('restoreSession',e)}q('authScreen').style.display='grid';return false}\n\n"""
s,n=re.subn(r"async function restoreSession\(\)\{.*?\n\nlet cloudSaveTimer",restore+'let cloudSaveTimer',s,count=1,flags=re.S);print('restore',n)
p.write_text(s)
