(function(){
  const URL='https://dhzptogrzuqreflcnsnb.supabase.co';
  const KEY='sb_publishable_DFmwh4k4-6RWDJnjCRNppA_TFrBkIxN';
  let client;
  const load=()=>window.supabase?Promise.resolve():new Promise((ok,fail)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=ok;s.onerror=fail;document.head.appendChild(s)});
  const saveLocal=()=>{try{localStorage.setItem('romano_db',JSON.stringify(db))}catch(e){}};
  async function profiles(){if(!client)return;try{let q=client.from('user_profiles').select('id,role,display_name,username,employee_id,active').eq('active',true);if(role==='FUNCIONÁRIO'){const id=localStorage.getItem('romano_auth_user_id');if(!id)return;q=q.eq('id',id)}else if(role!=='ADMIN')return;else q=q.eq('role','FUNCIONÁRIO');const r=await q;if(r.error||!r.data)return;r.data.forEach(p=>{if(!p.display_name)return;let e=db.employees.find(x=>x.username===p.username||x.name===p.display_name);if(!e){const nums=db.employees.map(x=>Number(String(x.id||'').replace(/\D/g,''))).filter(Number.isFinite);db.employees.push({id:p.employee_id||('F'+String(Math.max(0,...nums)+1).padStart(5,'0')),name:p.display_name,role:'Limpeza',phone:'',permission:'FUNCIONÁRIO',status:'Ativo',username:p.username||''})}else if(p.username)e.username=p.username});saveLocal();renderEmployees()}catch(e){console.error('ROMANO profiles',e)}}
  async function pull(){if(!client||role==='CLIENTE')return;try{let rows=[];if(role==='ADMIN'){const r=await client.from('service_jobs').select('*').order('updated_at',{ascending:false});if(r.error)throw r.error;rows=r.data||[]}else{const u=localStorage.getItem('romano_user')||'',n=localStorage.getItem('romano_display_name')||'';const rs=await Promise.all([u&&client.from('service_jobs').select('*').eq('responsible_username',u),n&&client.from('service_jobs').select('*').eq('responsible',n)].filter(Boolean));rs.forEach(r=>{if(!r.error)rows.push(...(r.data||[]))});const seen=new Set();rows=rows.filter(r=>!seen.has(r.id)&&(seen.add(r.id),true))}rows.forEach(r=>{const p=r.payload&&typeof r.payload==='object'?r.payload:{};const s={...p,id:r.id,responsible:p.responsible??r.responsible,status:r.status||p.status,startedAt:p.startedAt||'',finishedAt:p.finishedAt||'',responsible_username:p.responsible_username||r.responsible_username};const i=db.services.findIndex(x=>x.id===r.id);if(i<0)db.services.unshift(s);else db.services[i]={...db.services[i],...s}});saveLocal();renderServices();renderDashboard()}catch(e){console.error('ROMANO service pull',e)}}
  async function push(s){if(!client||!s?.id)return;try{const e=db.employees.find(x=>x.name===s.responsible);const u=s.responsible_username||e?.username||'';const ts=(d,t)=>d&&t?d+'T'+t+':00':null;const r=await client.from('service_jobs').upsert({id:s.id,client_id:s.clientId||null,responsible:s.responsible||null,responsible_username:u||null,status:s.status||'AGENDADO',started_at:ts(s.date,s.startedAt),finished_at:ts(s.date,s.finishedAt),payload:s,updated_at:new Date().toISOString()},{onConflict:'id'});if(r.error)console.error('ROMANO service push',r.error)}catch(e){console.error('ROMANO service push',e)}}
  async function boot(){try{await load();client=window.supabase.createClient(URL,KEY);await profiles();await pull();const wrap=(name,asyncFn)=>{const old=window[name];if(typeof old!=='function')return;if(asyncFn)window[name]=async function(){const out=await old.apply(this,arguments);const id=arguments[0];if(id)await push(db.services.find(x=>x.id===id));else if(db.services[0])await push(db.services[0]);return out};else window[name]=function(){const out=old.apply(this,arguments);setTimeout(()=>{if(db.services[0])push(db.services[0])},0);return out}};wrap('saveService',false);wrap('startService',true);wrap('finishService',true);wrap('saveIncident',true);wrap('saveMedia',true);const oldShow=window.showPage;window.showPage=function(n){const out=oldShow.apply(this,arguments);if(n==='services')pull();return out};setInterval(pull,15000)}catch(e){console.error('ROMANO sync boot',e)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
