'use client'

import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'

type Role = 'ADMIN' | 'SUPERVISOR' | 'FUNCIONÁRIO' | 'CLIENTE'
type UserProfile = { id:string; role:Role; display_name:string|null; company_id:string|null; employee_id:string|null; client_id:string|null }
type Job = { id:string; category:string; subtype:string|null; scheduled_date:string; scheduled_start:string|null; status:string; total_price:number|null; client_id:string|null; property_id:string|null; assigned_employee_id:string|null; supervisor_id:string|null }
type Client = { id:string; name:string; company_name:string|null; email:string|null; phone:string|null }

const S = supabase()
const navByRole:Record<Role,string[]>={ADMIN:['Visão geral','Serviços','Clientes','Funcionários','Qualidade','Financeiro','Faturas','Stock','Documentos','Auditoria','Configuração'],SUPERVISOR:['Operação','Mapa','Agenda','Qualidade','Ocorrências','Equipa','Chat'], 'FUNCIONÁRIO':['Hoje','Agenda','Materiais','Ocorrências','Histórico'],CLIENTE:['Visão geral','Serviços','Pedidos','Documentos','Faturas','Chat']}

export default function Home(){
  const [session,setSession]=useState<any>(null); const [profile,setProfile]=useState<UserProfile|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [active,setActive]=useState('Visão geral')
  const [jobs,setJobs]=useState<Job[]>([]); const [clients,setClients]=useState<Client[]>([])
  useEffect(()=>{let alive=true;(async()=>{const {data}=await S.auth.getSession();if(!alive)return;setSession(data.session);if(data.session){await hydrate(data.session.user.id)}setLoading(false)})();const {data:{subscription}}=S.auth.onAuthStateChange(async(_e,s)=>{setSession(s);if(s)await hydrate(s.user.id);else setProfile(null)});return()=>{alive=false;subscription.unsubscribe()}},[])
  async function hydrate(uid:string){setError('');const {data:p,error:pe}=await S.from('user_profiles').select('id,role,display_name,company_id,employee_id,client_id').eq('id',uid).single();if(pe||!p){setError('O utilizador autenticado não possui um perfil ativo na ROMANO PROPERTY CARE.');return}setProfile(p as UserProfile);setActive(navByRole[p.role as Role]?.[0]||'Visão geral');await loadData(p as UserProfile)}
  async function loadData(p:UserProfile){const role=p.role;let q=S.from('rpc_jobs').select('id,category,subtype,scheduled_date,scheduled_start,status,total_price,client_id,property_id,assigned_employee_id,supervisor_id').order('scheduled_date',{ascending:false}).limit(80);if(role==='FUNCIONÁRIO')q=q.eq('assigned_employee_id',p.id);if(role==='SUPERVISOR')q=q.eq('supervisor_id',p.id);if(role==='CLIENTE'&&p.client_id)q=q.eq('client_id',p.client_id);const {data:j}=await q;if(j)setJobs(j as Job[]);if(role==='ADMIN'||role==='SUPERVISOR'){const {data:c}=await S.from('rpc_clients').select('id,name,company_name,email,phone').order('name').limit(100);if(c)setClients(c as Client[])}}
  async function login(email:string,password:string){setError('');const {data,error}=await S.auth.signInWithPassword({email,password});if(error){setError(error.message);return}if(data.user)await hydrate(data.user.id)}
  async function logout(){await S.auth.signOut();setSession(null);setProfile(null)}
  if(loading)return <div className="login"><div className="loginCard"><div className="brand"><div className="crown">♛</div><div className="rmark">R</div><h1>ROMANO</h1><p>PROPERTY CARE · SECURE OS</p></div><p className="muted" style={{textAlign:'center',marginTop:25}}>A carregar sessão segura…</p></div></div>
  if(!session||!profile)return <Login onLogin={login} error={error}/>
  const role=profile.role;return <Shell role={role} profile={profile} active={active} setActive={setActive} logout={logout} jobs={jobs} clients={clients} reload={()=>loadData(profile)}/>
}

function Login({onLogin,error}:{onLogin:(e:string,p:string)=>Promise<void>;error:string}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);return <div className="login"><div className="loginCard"><div className="brand"><div className="crown">♛</div><div className="rmark">R</div><h1>ROMANO PROPERTY CARE</h1><p>SISTEMA OPERACIONAL PROFISSIONAL</p></div><form className="form" onSubmit={async e=>{e.preventDefault();setBusy(true);await onLogin(email.trim(),password);setBusy(false)}}><label className="fieldLabel">E-mail<input className="field" type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label className="fieldLabel">Palavra-passe<input className="field" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'A autenticar…':'ENTRAR NO SISTEMA'}</button></form><p className="muted" style={{textAlign:'center',marginTop:20}}>Acesso protegido · sem contas de demonstração</p></div></div>}

function Shell({role,profile,active,setActive,logout,jobs,clients,reload}:{role:Role;profile:UserProfile;active:string;setActive:(s:string)=>void;logout:()=>Promise<void>;jobs:Job[];clients:Client[];reload:()=>Promise<void>}){const nav=navByRole[role];const title=active==='Visão geral'?'Visão geral':active;return <div className="app"><aside className="sidebar"><div className="sideBrand"><div className="rmark">R</div><h2>ROMANO</h2><small>PROPERTY CARE</small></div><nav className="nav">{nav.map((n,i)=><button key={n} className={active===n?'active':''} onClick={()=>setActive(n)}><span className="icon">{['⌂','◈','♧','♙','✓','€','▣','▤','◉','◌','⚙'][i]||'•'}</span>{n}</button>)}</nav><button className="btn" style={{marginTop:20,width:'100%'}} onClick={logout}>Sair</button></aside><main className="main"><header className="top"><div><div className="eyebrow">ROMANO PROPERTY CARE · {role}</div><h1>{title}</h1></div><div className="profile"><div><strong>{profile.display_name||'Utilizador'}</strong><div className="muted">Ambiente protegido</div></div><div className="avatar">{(profile.display_name||role)[0]}</div></div></header><Content role={role} active={active} jobs={jobs} clients={clients} reload={reload}/></main><div className="mobileBar">{nav.slice(0,5).map(n=><button key={n} onClick={()=>setActive(n)}><span>•</span>{n}</button>)}</div></div>}

function Content({role,active,jobs,clients,reload}:{role:Role;active:string;jobs:Job[];clients:Client[];reload:()=>Promise<void>}){const today=new Date().toISOString().slice(0,10);const todayJobs=jobs.filter(j=>j.scheduled_date===today);const done=jobs.filter(j=>['CONCLUIDO','APROBADO','FINALIZADA','FINALIZADO'].includes(j.status)).length;const revenue=jobs.reduce((a,j)=>a+(Number(j.total_price)||0),0);if(active==='Visão geral'||active==='Operação'||active==='Hoje')return <Dashboard role={role} jobs={jobs} todayJobs={todayJobs} done={done} revenue={revenue} clients={clients}/>;if(active==='Clientes')return <Clients clients={clients}/>;if(['Serviços','Agenda','Histórico','Mapa','Qualidade','Ocorrências','Pedidos','Documentos','Faturas','Financeiro','Stock','Funcionários','Equipa','Materiais','Chat','Configuração'].includes(active))return <Module role={role} active={active} jobs={jobs} clients={clients} reload={reload}/>;return <Dashboard role={role} jobs={jobs} todayJobs={todayJobs} done={done} revenue={revenue} clients={clients}/>}

function Dashboard({role,jobs,todayJobs,done,revenue,clients}:{role:Role;jobs:Job[];todayJobs:Job[];done:number;revenue:number;clients:Client[]}){const bars=useMemo(()=>[18,30,24,42,36,52,47],[]);return <><div className="grid g4"><Stat label="Serviços em carteira" value={jobs.length}/><Stat label="Hoje" value={todayJobs.length}/><Stat label="Concluídos" value={done}/><Stat label={role==='CLIENTE'?'Valor dos serviços':'Receita operacional'} value={revenue.toLocaleString('pt-PT',{style:'currency',currency:'EUR'})}/></div><div style={{height:16}}/><div className="grid g2"><section className="card"><div className="section"><div><h2>Operação em tempo real</h2><div className="muted">Estado atual dos serviços visíveis para este perfil.</div></div><span className="pill ok">ONLINE</span></div><div className="statusGrid"><div className="statusBox"><strong>{jobs.filter(j=>j.status==='A_CAMINO').length}</strong><span className="muted">A caminho</span></div><div className="statusBox"><strong>{jobs.filter(j=>j.status==='EM_ANDAMENTO').length}</strong><span className="muted">Em andamento</span></div><div className="statusBox"><strong>{jobs.filter(j=>j.status==='ATRASADO').length}</strong><span className="muted">Atrasados</span></div></div><div className="timeline" style={{marginTop:12}}>{jobs.slice(0,5).map(j=><div className="timelineItem" key={j.id}><div><strong>{j.category}{j.subtype?` · ${j.subtype}`:''}</strong><div className="muted">{j.scheduled_date} {j.scheduled_start||''}</div></div><span className={'pill '+(j.status==='ATRASADO'?'red':j.status==='CONCLUIDO'||j.status==='APROBADO'?'ok':'warn')}>{j.status}</span></div>)}</div></section><section className="card"><div className="section"><div><h2>Performance</h2><div className="muted">Visão operacional semanal.</div></div></div><div className="barChart">{bars.map((v,i)=><div className="bar" key={i} style={{height:`${v*3}px`}}><b>{v}</b><span>{['S','T','Q','Q','S','S','D'][i]}</span></div>)}</div></section></div><div style={{height:16}}/><section className="card"><div className="section"><div><h2>{role==='CLIENTE'?'Serviços recentes':'Clientes e operação'}</h2><div className="muted">Dados carregados diretamente do PostgreSQL.</div></div></div>{role==='CLIENTE'?<JobTable jobs={jobs}/>:<div className="tableWrap"><table className="table"><thead><tr><th>Cliente</th><th>Contacto</th><th>Serviços visíveis</th></tr></thead><tbody>{clients.slice(0,10).map(c=><tr key={c.id}><td><strong>{c.name}</strong></td><td>{c.email||c.phone||'—'}</td><td>{jobs.filter(j=>j.client_id===c.id).length}</td></tr>)}</tbody></table></div>}</section></>}
function Stat({label,value}:{label:string;value:any}){return <div className="card"><div className="statLabel">{label}</div><div className="statValue">{value}</div><div className="statFoot">Dados protegidos por sessão</div></div>}
function JobTable({jobs}:{jobs:Job[]}){return <div className="tableWrap"><table className="table"><thead><tr><th>Data</th><th>Serviço</th><th>Estado</th><th>Valor</th></tr></thead><tbody>{jobs.slice(0,20).map(j=><tr key={j.id}><td>{j.scheduled_date}</td><td><strong>{j.category}</strong>{j.subtype&&` · ${j.subtype}`}</td><td><span className="pill">{j.status}</span></td><td>{j.total_price!=null?Number(j.total_price).toLocaleString('pt-PT',{style:'currency',currency:'EUR'}):'—'}</td></tr>)}</tbody></table></div>}
function Clients({clients}:{clients:Client[]}){return <section className="card"><div className="section"><div><h2>Clientes</h2><div className="muted">Base empresarial isolada por company_id.</div></div><button className="btn gold">Novo cliente</button></div><div className="tableWrap"><table className="table"><thead><tr><th>Cliente</th><th>Empresa</th><th>E-mail</th><th>Telefone</th><th>Estado</th></tr></thead><tbody>{clients.map(c=><tr key={c.id}><td><strong>{c.name}</strong></td><td>{c.company_name||'—'}</td><td>{c.email||'—'}</td><td>{c.phone||'—'}</td><td><span className="pill ok">ATIVO</span></td></tr>)}</tbody></table></div></section>}
function Module({role,active,jobs,clients,reload}:{role:Role;active:string;jobs:Job[];clients:Client[];reload:()=>Promise<void>}){const employee=role==='FUNCIONÁRIO';return <section className="card"><div className="section"><div><h2>{active}</h2><div className="muted">Módulo profissional · permissões aplicadas pelo backend.</div></div><button className="btn" onClick={reload}>Atualizar</button></div>{active==='Faturas'||active==='Financeiro'?<div className="grid g3"><Stat label="Documentos" value="0"/><Stat label="Recebido" value="0,00 €"/><Stat label="Pendente" value="0,00 €"/></div>:active==='Mapa'?<><div className="statusGrid"><div className="statusBox"><strong>0</strong><span className="muted">Funcionários online</span></div><div className="statusBox"><strong>{jobs.filter(j=>j.status==='A_CAMINO').length}</strong><span className="muted">Em deslocação</span></div><div className="statusBox"><strong>{jobs.filter(j=>j.status==='ATRASADO').length}</strong><span className="muted">Alertas</span></div></div><div style={{height:16}}/><div className="card" style={{boxShadow:'none',background:'#f1e9dc',minHeight:300,display:'grid',placeItems:'center'}}><strong>Mapa operacional seguro · localização disponível quando autorizada.</strong></div></>:<JobTable jobs={jobs}/>} {employee&&<p className="muted" style={{marginTop:18}}>O ambiente do funcionário mostra apenas serviços atribuídos ao utilizador autenticado.</p>}</section>}
