'use client'

import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'

type Role = 'ADMIN' | 'SUPERVISOR' | 'FUNCIONÁRIO' | 'CLIENTE'
type UserProfile = { id:string; role:Role; display_name:string|null; company_id:string|null; employee_id:string|null; client_id:string|null }
type Job = { id:string; category:string; subtype:string|null; typology:string|null; scheduled_date:string; scheduled_start:string|null; status:string; total_price:number|null; client_id:string|null; property_id:string|null; assigned_employee_id:string|null; supervisor_id:string|null; instructions?:string|null }
type Client = { id:string; name:string; company_name:string|null; email:string|null; phone:string|null }
type Checklist = { id:string; item_id:string; completed:boolean; note:string|null; item?:{label?:string; title?:string; description?:string}|null }
type Media = { id:string; stage:string; media_type:string; storage_path:string; caption:string|null }

const S = supabase()
const navByRole:Record<Role,string[]>={
  ADMIN:['Visão geral','Serviços','Clientes','Funcionários','Qualidade','Financeiro','Faturas','Stock','Documentos','Auditoria','Configuração'],
  SUPERVISOR:['Operação','Mapa','Agenda','Qualidade','Ocorrências','Equipa','Chat'],
  'FUNCIONÁRIO':['Hoje','Agenda','Materiais','Ocorrências','Histórico'],
  CLIENTE:['Visão geral','Serviços','Pedidos','Documentos','Faturas','Chat']
}

export default function Home(){
  const [session,setSession]=useState<any>(null); const [profile,setProfile]=useState<UserProfile|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [active,setActive]=useState('Visão geral');
  const [jobs,setJobs]=useState<Job[]>([]); const [clients,setClients]=useState<Client[]>([]); const [selectedJob,setSelectedJob]=useState<Job|null>(null)
  useEffect(()=>{let alive=true;(async()=>{const {data}=await S.auth.getSession();if(!alive)return;setSession(data.session);if(data.session)await hydrate(data.session.user.id);setLoading(false)})();const {data:{subscription}}=S.auth.onAuthStateChange(async(_e,s)=>{setSession(s);if(s)await hydrate(s.user.id);else setProfile(null)});return()=>{alive=false;subscription.unsubscribe()}},[])
  async function hydrate(uid:string){setError('');const {data:p,error:pe}=await S.from('user_profiles').select('id,role,display_name,company_id,employee_id,client_id').eq('id',uid).single();if(pe||!p){setError('O utilizador autenticado não possui um perfil ativo na ROMANO PROPERTY CARE.');return}setProfile(p as UserProfile);setActive(navByRole[p.role as Role]?.[0]||'Visão geral');await loadData(p as UserProfile)}
  async function loadData(p:UserProfile){const role=p.role;let q=S.from('rpc_jobs').select('id,category,subtype,typology,scheduled_date,scheduled_start,status,total_price,client_id,property_id,assigned_employee_id,supervisor_id,instructions').order('scheduled_date',{ascending:false}).limit(100);if(role==='FUNCIONÁRIO')q=q.eq('assigned_employee_id',p.id);if(role==='SUPERVISOR')q=q.eq('supervisor_id',p.id);if(role==='CLIENTE'&&p.client_id)q=q.eq('client_id',p.client_id);const {data:j,error:je}=await q;if(je)setError(je.message);if(j)setJobs(j as Job[]);if(role==='ADMIN'||role==='SUPERVISOR'){const {data:c}=await S.from('rpc_clients').select('id,name,company_name,email,phone').order('name').limit(100);if(c)setClients(c as Client[])}}
  async function login(email:string,password:string){setError('');const {data,error}=await S.auth.signInWithPassword({email,password});if(error){setError(error.message);return}if(data.user)await hydrate(data.user.id)}
  async function logout(){await S.auth.signOut();setSession(null);setProfile(null)}
  if(loading)return <div className="login"><div className="loginCard"><Brand/><p className="muted center">A carregar sessão segura…</p></div></div>
  if(!session||!profile)return <Login onLogin={login} error={error}/>
  const role=profile.role;return <Shell role={role} profile={profile} active={active} setActive={setActive} logout={logout} jobs={jobs} clients={clients} reload={()=>loadData(profile)} selectedJob={selectedJob} setSelectedJob={setSelectedJob}/>
}

function Brand(){return <div className="brand"><div className="crown">♛</div><div className="rmark">R</div><h1>ROMANO PROPERTY CARE</h1><p>SISTEMA OPERACIONAL PROFISSIONAL</p></div>}
function Login({onLogin,error}:{onLogin:(e:string,p:string)=>Promise<void>;error:string}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);return <div className="login"><div className="loginCard"><Brand/><form className="form" onSubmit={async e=>{e.preventDefault();setBusy(true);await onLogin(email.trim(),password);setBusy(false)}}><label className="fieldLabel">E-mail<input className="field" type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label className="fieldLabel">Palavra-passe<input className="field" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'A autenticar…':'ENTRAR NO SISTEMA'}</button></form><p className="muted center">Acesso protegido · sem contas de demonstração</p></div></div>}

function Shell({role,profile,active,setActive,logout,jobs,clients,reload,selectedJob,setSelectedJob}:{role:Role;profile:UserProfile;active:string;setActive:(s:string)=>void;logout:()=>Promise<void>;jobs:Job[];clients:Client[];reload:()=>Promise<void>;selectedJob:Job|null;setSelectedJob:(j:Job|null)=>void}){const nav=navByRole[role];const title=active==='Visão geral'?'Visão geral':active;return <div className="app"><aside className="sidebar"><div className="sideBrand"><div className="rmark">R</div><h2>ROMANO</h2><small>PROPERTY CARE</small></div><nav className="nav">{nav.map((n,i)=><button key={n} className={active===n?'active':''} onClick={()=>setActive(n)}><span className="icon">{['⌂','◈','♧','♙','✓','€','▣','▤','◉','◌','⚙'][i]||'•'}</span>{n}</button>)}</nav><button className="btn" style={{marginTop:20,width:'100%'}} onClick={logout}>Sair</button></aside><main className="main"><header className="top"><div><div className="eyebrow">ROMANO PROPERTY CARE · {role}</div><h1>{title}</h1></div><div className="profile"><div><strong>{profile.display_name||'Utilizador'}</strong><div className="muted">Ambiente protegido</div></div><div className="avatar">{(profile.display_name||role)[0]}</div></div></header><Content role={role} active={active} jobs={jobs} clients={clients} reload={reload} selectedJob={selectedJob} setSelectedJob={setSelectedJob}/></main><div className="mobileBar">{nav.slice(0,5).map(n=><button key={n} onClick={()=>setActive(n)}><span>•</span>{n}</button>)}</div></div>}

function Content({role,active,jobs,clients,reload,selectedJob,setSelectedJob}:{role:Role;active:string;jobs:Job[];clients:Client[];reload:()=>Promise<void>;selectedJob:Job|null;setSelectedJob:(j:Job|null)=>void}){const today=new Date().toISOString().slice(0,10);const todayJobs=jobs.filter(j=>j.scheduled_date===today);const done=jobs.filter(j=>['CONCLUIDO','APROBADO','FINALIZADA','FINALIZADO'].includes(j.status)).length;const revenue=jobs.reduce((a,j)=>a+(Number(j.total_price)||0),0);if(role==='FUNCIONÁRIO'&&(active==='Hoje'||active==='Agenda'||active==='Materiais'||active==='Ocorrências'||active==='Histórico'))return <EmployeeHome active={active} jobs={jobs} today={today} onSelect={setSelectedJob} selectedJob={selectedJob} reload={reload}/>;if(active==='Visão geral'||active==='Operação')return <Dashboard role={role} jobs={jobs} todayJobs={todayJobs} done={done} revenue={revenue} clients={clients} onSelect={setSelectedJob}/>;if(active==='Clientes')return <Clients clients={clients}/>;return <Module role={role} active={active} jobs={jobs} clients={clients} reload={reload} onSelect={setSelectedJob}/>}

function EmployeeHome({active,jobs,today,onSelect,selectedJob,reload}:{active:string;jobs:Job[];today:string;onSelect:(j:Job)=>void;selectedJob:Job|null;reload:()=>Promise<void>}){const todayJobs=jobs.filter(j=>j.scheduled_date===today);return <>{active==='Hoje'?<><div className="grid g4"><Stat label="Serviços de hoje" value={todayJobs.length}/><Stat label="A caminho" value={todayJobs.filter(j=>j.status==='A_CAMINO').length}/><Stat label="Em andamento" value={todayJobs.filter(j=>['EM_ANDAMENTO','INICIADO'].includes(j.status)).length}/><Stat label="Concluídos" value={todayJobs.filter(j=>['CONCLUIDO','FINALIZADO','APROBADO'].includes(j.status)).length}/></div><div className="serviceList">{todayJobs.length?todayJobs.map(j=><JobCard key={j.id} job={j} onClick={()=>onSelect(j)}/>):<section className="card empty"><h2>Nenhum serviço hoje</h2><p className="muted">Quando um serviço for atribuído, aparecerá aqui automaticamente.</p></section>}</div></>:<section className="card"><div className="section"><div><h2>{active}</h2><div className="muted">Fluxo operacional ligado ao backend.</div></div><button className="btn" onClick={reload}>Atualizar</button></div>{selectedJob?<ServiceExecution job={selectedJob} close={()=>onSelect(selectedJob)} reload={reload}/>:<div className="serviceList">{jobs.map(j=><JobCard key={j.id} job={j} onClick={()=>onSelect(j)}/>)}</div>}</section>}</>}

function JobCard({job,onClick}:{job:Job;onClick:()=>void}){return <button className="jobCard" onClick={onClick}><div><div className="eyebrow">{job.scheduled_date} {job.scheduled_start||''}</div><h3>{job.category}{job.subtype?` · ${job.subtype}`:''}</h3><p className="muted">{job.typology||'Serviço profissional'} · {job.status}</p></div><span className="pill">ABRIR →</span></button>}

function ServiceExecution({job,close,reload}:{job:Job;close:()=>void;reload:()=>Promise<void>}){const [checklist,setChecklist]=useState<Checklist[]>([]);const [media,setMedia]=useState<Media[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [geo,setGeo]=useState<{lat:number;lng:number}|null>(null);const [loading,setLoading]=useState(true);const [stage,setStage]=useState<'ANTES'|'DEPOIS'>('ANTES');
  async function load(){setLoading(true);const {data:c}=await S.from('rpc_job_checklist').select('id,item_id,completed,note, item:rpc_checklist_items(label,title,description)').eq('job_id',job.id);if(c)setChecklist(c as any);const {data:m}=await S.from('rpc_media').select('id,stage,media_type,storage_path,caption').eq('job_id',job.id).order('created_at');if(m)setMedia(m as Media[]);setLoading(false)}
  useEffect(()=>{load()},[job.id])
  function getLocation(){return new Promise<GeolocationPosition>((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Geolocalização não disponível neste dispositivo.'));navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:0})})}
  async function start(){setBusy(true);setMessage('A validar localização…');try{const p=await getLocation();setGeo({lat:p.coords.latitude,lng:p.coords.longitude});const {error}=await S.from('rpc_employee_locations').insert({employee_id:(await S.auth.getUser()).data.user?.id,job_id:job.id,latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_m:p.coords.accuracy});if(error)throw error;const r=await S.rpc('rpc_job_time_event',{p_job_id:job.id,p_event_type:'START'});if(r.error)throw r.error;setMessage('Serviço iniciado com localização registada.');await reload()}catch(e:any){setMessage(e.message||'Não foi possível iniciar o serviço.')}finally{setBusy(false)}}
  async function toggle(item:Checklist){setBusy(true);const r=await S.rpc('rpc_set_job_checklist_item',{p_job_id:job.id,p_item_id:item.item_id,p_completed:!item.completed,p_note:item.note||null});if(r.error)setMessage(r.error.message);else setChecklist(x=>x.map(i=>i.id===item.id?{...i,completed:!i.completed}:i));setBusy(false)}
  async function upload(file:File){setBusy(true);setMessage('A enviar evidência privada…');try{const user=(await S.auth.getUser()).data.user;if(!user)throw new Error('Sessão expirada.');const ext=file.name.split('.').pop()||'jpg';const path=`companies/${user.id}/jobs/${job.id}/${stage.toLowerCase()}-${crypto.randomUUID()}.${ext}`;const up=await S.storage.from('rpc-media').upload(path,file,{contentType:file.type,upsert:false});if(up.error)throw up.error;const r=await S.rpc('rpc_register_service_media',{p_job_id:job.id,p_media_type:file.type.startsWith('video')?'VIDEO':'PHOTO',p_stage:stage,p_storage_path:path,p_caption:null});if(r.error)throw r.error;await load();setMessage(`${stage} concluído: evidência guardada.`)}catch(e:any){setMessage(e.message||'Falha no envio.')}finally{setBusy(false)}}
  async function finish(){setBusy(true);setMessage('A validar requisitos de conclusão…');try{const before=media.filter(m=>m.stage==='ANTES').length;const after=media.filter(m=>m.stage==='DEPOIS').length;const incomplete=checklist.filter(c=>!c.completed).length;if(before<1)throw new Error('É obrigatório enviar pelo menos 1 foto ANTES.');if(after<1)throw new Error('É obrigatório enviar pelo menos 1 foto DEPOIS.');if(incomplete)throw new Error(`Faltam ${incomplete} itens do checklist.`);const r=await S.rpc('rpc_job_time_event',{p_job_id:job.id,p_event_type:'FINISH'});if(r.error)throw r.error;setMessage('Serviço finalizado. A prova de execução permanece associada ao serviço.');await reload()}catch(e:any){setMessage(e.message||'Não foi possível finalizar.')}finally{setBusy(false)}}
  if(loading)return <p className="muted">A carregar checklist e evidências…</p>;
  const started=['EM_ANDAMENTO','INICIADO','PAUSADO'].includes(job.status);return <div className="execution"><div className="section"><div><div className="eyebrow">{job.scheduled_date} · {job.scheduled_start||'horário aberto'}</div><h2>{job.category}{job.subtype?` · ${job.subtype}`:''}</h2></div><button className="btn" onClick={close}>Fechar</button></div>{message&&<div className={message.toLowerCase().includes('obrigatório')||message.toLowerCase().includes('falha')?'error':'notice'}>{message}</div>}<div className="executionGrid"><div className="card inner"><h3>1 · Presença</h3><p className="muted">O início exige GPS do dispositivo e registo no servidor.</p><button className="primary" disabled={busy||started} onClick={start}>{started?'SERVIÇO INICIADO':'INICIAR SERVIÇO'}</button>{geo&&<small className="muted">GPS registado · ± localização com precisão {Math.round(geo.lng*0+0)} m</small>}</div><div className="card inner"><h3>2 · Evidências</h3><div className="tabs"><button className={stage==='ANTES'?'tab active':''} onClick={()=>setStage('ANTES')}>ANTES ({media.filter(m=>m.stage==='ANTES').length})</button><button className={stage==='DEPOIS'?'tab active':''} onClick={()=>setStage('DEPOIS')}>DEPOIS ({media.filter(m=>m.stage==='DEPOIS').length})</button></div><label className="upload"><input type="file" accept="image/*,video/*" capture="environment" disabled={busy||!started} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/>{started?'＋ Adicionar foto/vídeo':'Inicie o serviço para enviar evidências'}</label></div></div><div className="card inner"><div className="section"><div><h3>3 · Checklist</h3><p className="muted">Todos os itens devem estar concluídos antes do encerramento.</p></div><span className="pill">{checklist.filter(x=>x.completed).length}/{checklist.length}</span></div>{checklist.length?<div className="checklist">{checklist.map(c=><button className="check" key={c.id} onClick={()=>toggle(c)} disabled={busy}><span className={c.completed?'checkmark done':'checkmark'}>{c.completed?'✓':''}</span><span><strong>{c.item?.label||c.item?.title||'Item do checklist'}</strong>{c.item?.description&&<small className="muted">{c.item.description}</small>}</span></button>)}</div>:<p className="muted">Nenhum checklist foi atribuído a este serviço.</p>}</div><div className="card finishBox"><div><h3>4 · Finalizar</h3><p className="muted">Sem evidências ANTES/DEPOIS e checklist completo, o sistema bloqueia a conclusão.</p></div><button className="primary" disabled={busy||!started} onClick={finish}>FINALIZAR SERVIÇO</button></div></div>}

function Dashboard({role,jobs,todayJobs,done,revenue,clients,onSelect}:{role:Role;jobs:Job[];todayJobs:Job[];done:number;revenue:number;clients:Client[];onSelect:(j:Job)=>void}){const bars=useMemo(()=>[18,30,24,42,36,52,47],[]);return <><div className="grid g4"><Stat label="Serviços em carteira" value={jobs.length}/><Stat label="Hoje" value={todayJobs.length}/><Stat label="Concluídos" value={done}/><Stat label={role==='CLIENTE'?'Valor dos serviços':'Receita operacional'} value={revenue.toLocaleString('pt-PT',{style:'currency',currency:'EUR'})}/></div><div className="space"/><div className="grid g2"><section className="card"><div className="section"><div><h2>Operação em tempo real</h2><div className="muted">Estado atual dos serviços visíveis para este perfil.</div></div><span className="pill ok">ONLINE</span></div><div className="statusGrid"><div className="statusBox"><strong>{jobs.filter(j=>j.status==='A_CAMINO').length}</strong><span className="muted">A caminho</span></div><div className="statusBox"><strong>{jobs.filter(j=>['EM_ANDAMENTO','INICIADO'].includes(j.status)).length}</strong><span className="muted">Em andamento</span></div><div className="statusBox"><strong>{jobs.filter(j=>j.status==='ATRASADO').length}</strong><span className="muted">Atrasados</span></div></div><div className="timeline">{jobs.slice(0,6).map(j=><button className="timelineItem" key={j.id} onClick={()=>onSelect(j)}><div><strong>{j.category}{j.subtype?` · ${j.subtype}`:''}</strong><div className="muted">{j.scheduled_date} {j.scheduled_start||''}</div></div><span className="pill">{j.status}</span></button>)}</div></section><section className="card"><div className="section"><div><h2>Performance</h2><div className="muted">Visão operacional semanal.</div></div></div><div className="barChart">{bars.map((v,i)=><div className="bar" key={i} style={{height:`${v*3}px`}}><b>{v}</b><span>{['S','T','Q','Q','S','S','D'][i]}</span></div>)}</div></section></div><div className="space"/><section className="card"><div className="section"><div><h2>{role==='CLIENTE'?'Serviços recentes':'Clientes e operação'}</h2><div className="muted">Dados carregados diretamente do PostgreSQL.</div></div></div>{role==='CLIENTE'?<JobTable jobs={jobs} onSelect={onSelect}/>:<div className="tableWrap"><table className="table"><thead><tr><th>Cliente</th><th>Contacto</th><th>Serviços visíveis</th></tr></thead><tbody>{clients.slice(0,10).map(c=><tr key={c.id}><td><strong>{c.name}</strong></td><td>{c.email||c.phone||'—'}</td><td>{jobs.filter(j=>j.client_id===c.id).length}</td></tr>)}</tbody></table></div>}</section></>}
function Stat({label,value}:{label:string;value:any}){return <div className="card"><div className="statLabel">{label}</div><div className="statValue">{value}</div><div className="statFoot">Dados protegidos por sessão</div></div>}
function JobTable({jobs,onSelect}:{jobs:Job[];onSelect?:(j:Job)=>void}){return <div className="tableWrap"><table className="table"><thead><tr><th>Data</th><th>Serviço</th><th>Estado</th><th>Valor</th></tr></thead><tbody>{jobs.slice(0,20).map(j=><tr key={j.id} onClick={()=>onSelect?.(j)} style={{cursor:onSelect?'pointer':'default'}}><td>{j.scheduled_date}</td><td><strong>{j.category}</strong>{j.subtype&&` · ${j.subtype}`}</td><td><span className="pill">{j.status}</span></td><td>{j.total_price!=null?Number(j.total_price).toLocaleString('pt-PT',{style:'currency',currency:'EUR'}):'—'}</td></tr>)}</tbody></table></div>}
function Clients({clients}:{clients:Client[]}){return <section className="card"><div className="section"><div><h2>Clientes</h2><div className="muted">Base empresarial isolada por company_id.</div></div><button className="btn gold">Novo cliente</button></div><div className="tableWrap"><table className="table"><thead><tr><th>Cliente</th><th>Empresa</th><th>E-mail</th><th>Telefone</th><th>Estado</th></tr></thead><tbody>{clients.map(c=><tr key={c.id}><td><strong>{c.name}</strong></td><td>{c.company_name||'—'}</td><td>{c.email||'—'}</td><td>{c.phone||'—'}</td><td><span className="pill ok">ATIVO</span></td></tr>)}</tbody></table></div></section>}
function Module({role,active,jobs,clients,reload,onSelect}:{role:Role;active:string;jobs:Job[];clients:Client[];reload:()=>Promise<void>;onSelect:(j:Job)=>void}){return <section className="card"><div className="section"><div><h2>{active}</h2><div className="muted">Módulo profissional · dados reais e permissões do backend.</div></div><button className="btn" onClick={reload}>Atualizar</button></div>{active==='Faturas'||active==='Financeiro'?<div className="grid g3"><Stat label="Documentos" value="—"/><Stat label="Recebido" value="—"/><Stat label="Pendente" value="—"/></div>:active==='Mapa'?<><div className="statusGrid"><div className="statusBox"><strong>—</strong><span className="muted">Funcionários online</span></div><div className="statusBox"><strong>{jobs.filter(j=>j.status==='A_CAMINO').length}</strong><span className="muted">Em deslocação</span></div><div className="statusBox"><strong>{jobs.filter(j=>j.status==='ATRASADO').length}</strong><span className="muted">Alertas</span></div></div><div className="space"/><div className="mapPlaceholder"><strong>Mapa operacional</strong><span>Localizações são privadas e só aparecem conforme as permissões do perfil.</span></div></>:<JobTable jobs={jobs} onSelect={onSelect}/>}</section>}
